# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zdjecie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('szerokosc', models.IntegerField(default=0)),
                ('wysokosc', models.IntegerField(default=0)),
                ('obrazek', models.ImageField(height_field='wysokosc', upload_to='', width_field='szerokosc')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
